import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const admin = await prisma.user.findUnique({ where: { email: "admin@saudiacareers.com" } });
  if (!admin) throw new Error("Admin user not found. Run the main seed first.");

  const deadline = (daysFromNow) => {
    const d = new Date();
    d.setDate(d.getDate() + daysFromNow);
    return d;
  };

  const jobs = [
    {
      title: "React Developer",
      companyName: "Saudi Digital Co.",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 12,000 – 16,000 / month",
      description: "Build and maintain modern React applications for enterprise clients across the Kingdom.",
      requiredSkills: "React, JavaScript, TypeScript, CSS, REST APIs",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(45),
      createdBy: admin.id,
    },
    {
      title: "Node.js Backend Developer",
      companyName: "Tamara Financial",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 15,000 – 20,000 / month",
      description: "Design scalable REST APIs and microservices for a fast-growing fintech platform.",
      requiredSkills: "Node.js, Express, PostgreSQL, Redis, Docker",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(30),
      createdBy: admin.id,
    },
    {
      title: "Full Stack Developer",
      companyName: "Noon Commerce",
      location: "Riyadh",
      industry: "E-commerce",
      employmentType: "Full-time",
      experienceRequired: "3-6 years",
      salaryRange: "SAR 14,000 – 19,000 / month",
      description: "Own features end-to-end across our React frontend and Node.js backend.",
      requiredSkills: "React, Node.js, MongoDB, AWS, TypeScript",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(60),
      createdBy: admin.id,
    },
    {
      title: "DevOps Engineer",
      companyName: "STC Pay",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "4-7 years",
      salaryRange: "SAR 18,000 – 24,000 / month",
      description: "Build and maintain CI/CD pipelines and cloud infrastructure at scale.",
      requiredSkills: "Kubernetes, Docker, AWS, Terraform, Jenkins",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(40),
      createdBy: admin.id,
    },
    {
      title: "Mobile Developer (iOS)",
      companyName: "Jahez Technologies",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "2-5 years",
      salaryRange: "SAR 13,000 – 18,000 / month",
      description: "Develop and maintain our iOS delivery application used by millions of Saudis.",
      requiredSkills: "Swift, UIKit, SwiftUI, Xcode, REST APIs",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(50),
      createdBy: admin.id,
    },
    {
      title: "Data Scientist",
      companyName: "Elm Company",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "3-6 years",
      salaryRange: "SAR 16,000 – 22,000 / month",
      description: "Develop ML models and data pipelines to power digital government services.",
      requiredSkills: "Python, Scikit-learn, TensorFlow, SQL, Spark",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(35),
      createdBy: admin.id,
    },
    {
      title: "Cybersecurity Analyst",
      companyName: "Saudi Aramco",
      location: "Dammam",
      industry: "Oil & Gas",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 17,000 – 23,000 / month",
      description: "Monitor, detect and respond to security incidents across critical infrastructure.",
      requiredSkills: "SIEM, Splunk, Incident Response, Network Security, CISSP",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(55),
      createdBy: admin.id,
    },
    {
      title: "UI/UX Designer",
      companyName: "Mrsool",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 10,000 – 14,000 / month",
      description: "Design intuitive mobile and web experiences for our delivery super-app.",
      requiredSkills: "Figma, User Research, Prototyping, Design Systems, Accessibility",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(42),
      createdBy: admin.id,
    },
    {
      title: "Product Manager",
      companyName: "Stc",
      location: "Riyadh",
      industry: "Telecommunications",
      employmentType: "Full-time",
      experienceRequired: "4-7 years",
      salaryRange: "SAR 18,000 – 26,000 / month",
      description: "Drive roadmap and strategy for our consumer digital products portfolio.",
      requiredSkills: "Product Strategy, Agile, Data Analysis, Stakeholder Management",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(38),
      createdBy: admin.id,
    },
    {
      title: "Sales Executive",
      companyName: "Gulf Services Group",
      location: "Jeddah",
      industry: "Business Services",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 6,000 – 9,000 + commission",
      description: "Drive B2B sales for our facility management and outsourcing solutions.",
      requiredSkills: "B2B Sales, CRM, Negotiation, Communication, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(25),
      createdBy: admin.id,
    },
    {
      title: "Accountant",
      companyName: "KPMG Saudi Arabia",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 8,000 – 11,000 / month",
      description: "Manage financial records, reconciliations and support audit processes.",
      requiredSkills: "SAP, Excel, IFRS, Financial Reporting, Taxation",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(30),
      createdBy: admin.id,
    },
    {
      title: "Financial Analyst",
      companyName: "Riyad Bank",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 12,000 – 16,000 / month",
      description: "Analyze financial data and prepare investment and risk reports for senior management.",
      requiredSkills: "Excel, Financial Modeling, Bloomberg, CFA, Risk Analysis",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(45),
      createdBy: admin.id,
    },
    {
      title: "HR Manager",
      companyName: "Almarai",
      location: "Riyadh",
      industry: "Food & Beverage",
      employmentType: "Full-time",
      experienceRequired: "6-10 years",
      salaryRange: "SAR 18,000 – 24,000 / month",
      description: "Lead HR operations for a large production facility including recruitment and payroll.",
      requiredSkills: "HRMS, Recruitment, Labor Law, Performance Management, Saudi Labor Law",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(60),
      createdBy: admin.id,
    },
    {
      title: "Marketing Manager",
      companyName: "Luxury Car Trading",
      location: "Jeddah",
      industry: "Automotive",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 15,000 – 20,000 / month",
      description: "Lead brand strategy and digital campaigns for a premium automotive dealership.",
      requiredSkills: "Digital Marketing, Social Media, Campaign Management, Analytics, Brand Strategy",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(40),
      createdBy: admin.id,
    },
    {
      title: "Civil Engineer",
      companyName: "Saudi Binladin Group",
      location: "Mecca",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "3-6 years",
      salaryRange: "SAR 10,000 – 15,000 / month",
      description: "Oversee structural design and site supervision on large-scale construction projects.",
      requiredSkills: "AutoCAD, Structural Analysis, Project Management, MS Project, OSHA",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(50),
      createdBy: admin.id,
    },
    {
      title: "Electrical Engineer",
      companyName: "Saudi Aramco",
      location: "Dammam",
      industry: "Oil & Gas",
      employmentType: "Full-time",
      experienceRequired: "4-7 years",
      salaryRange: "SAR 16,000 – 22,000 / month",
      description: "Design and maintain HV electrical systems for refinery operations.",
      requiredSkills: "ETAP, HV Systems, PLC, AutoCAD Electrical, IEC Standards",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(35),
      createdBy: admin.id,
    },
    {
      title: "Mechanical Engineer",
      companyName: "Sabic",
      location: "Jubail",
      industry: "Petrochemicals",
      employmentType: "Full-time",
      experienceRequired: "3-6 years",
      salaryRange: "SAR 13,000 – 18,000 / month",
      description: "Support plant equipment reliability and rotating machinery maintenance programs.",
      requiredSkills: "SolidWorks, Rotating Equipment, RCM, API Standards, CMMS",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(55),
      createdBy: admin.id,
    },
    {
      title: "Project Manager",
      companyName: "Al-Futtaim Group",
      location: "Riyadh",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "6-10 years",
      salaryRange: "SAR 20,000 – 28,000 / month",
      description: "Manage end-to-end delivery of mixed-use development projects across Vision 2030 initiatives.",
      requiredSkills: "PMP, MS Project, Primavera P6, Risk Management, Stakeholder Communication",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(45),
      createdBy: admin.id,
    },
    {
      title: "Supply Chain Analyst",
      companyName: "Almarai",
      location: "Riyadh",
      industry: "Food & Beverage",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 9,000 – 13,000 / month",
      description: "Optimize inventory levels and procurement processes across a national distribution network.",
      requiredSkills: "SAP MM, Demand Forecasting, Excel, ERP, Logistics",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(30),
      createdBy: admin.id,
    },
    {
      title: "Graphic Designer",
      companyName: "MBC Group",
      location: "Riyadh",
      industry: "Media & Entertainment",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 7,000 – 10,000 / month",
      description: "Create on-brand visuals for broadcast, digital, and social media channels.",
      requiredSkills: "Photoshop, Illustrator, After Effects, Brand Guidelines, Motion Graphics",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(20),
      createdBy: admin.id,
    },
    {
      title: "Content Writer (Arabic)",
      companyName: "Thmanyah",
      location: "Riyadh",
      industry: "Media & Entertainment",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 6,000 – 9,000 / month",
      description: "Produce engaging Arabic editorial content for podcasts, digital platforms and social media.",
      requiredSkills: "Arabic Writing, Storytelling, SEO, Content Strategy, Social Media",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(25),
      createdBy: admin.id,
    },
    {
      title: "Registered Nurse",
      companyName: "King Faisal Specialist Hospital",
      location: "Riyadh",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 8,000 – 12,000 / month",
      description: "Provide direct patient care in a tertiary referral hospital setting.",
      requiredSkills: "ICU, Patient Care, IV Therapy, BLS, ACLS",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(60),
      createdBy: admin.id,
    },
    {
      title: "Pharmacist",
      companyName: "Al Nahdi Pharmacy",
      location: "Jeddah",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "0-2 years",
      salaryRange: "SAR 7,000 – 10,000 / month",
      description: "Dispense medications, counsel patients and ensure compliance with Saudi SFDA regulations.",
      requiredSkills: "Pharmacy Practice, SFDA Regulations, Patient Counseling, Inventory Management",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(40),
      createdBy: admin.id,
    },
    {
      title: "Doctor – General Practitioner",
      companyName: "Mouwasat Hospital",
      location: "Dammam",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "3-6 years",
      salaryRange: "SAR 20,000 – 30,000 / month",
      description: "Provide comprehensive outpatient medical consultations and manage chronic disease cases.",
      requiredSkills: "Clinical Assessment, EMR, Chronic Disease Management, Arabic, SCFHS License",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(50),
      createdBy: admin.id,
    },
    {
      title: "Teacher – Mathematics",
      companyName: "GEMS Education Saudi",
      location: "Riyadh",
      industry: "Education",
      employmentType: "Full-time",
      experienceRequired: "2-5 years",
      salaryRange: "SAR 9,000 – 13,000 / month",
      description: "Teach secondary mathematics following a British curriculum to KS3 and KS4 students.",
      requiredSkills: "Mathematics, Curriculum Planning, Classroom Management, British Curriculum, IGCSE",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(30),
      createdBy: admin.id,
    },
    {
      title: "English Language Instructor",
      companyName: "British Council",
      location: "Riyadh",
      industry: "Education",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 8,000 – 11,000 / month",
      description: "Deliver IELTS preparation and general English courses to adult learners.",
      requiredSkills: "CELTA, IELTS, Lesson Planning, Adult Education, English Teaching",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(35),
      createdBy: admin.id,
    },
    {
      title: "Logistics Coordinator",
      companyName: "DHL Saudi Arabia",
      location: "Jeddah",
      industry: "Logistics",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 7,000 – 10,000 / month",
      description: "Coordinate import, export and customs clearance operations through Jeddah Islamic Port.",
      requiredSkills: "Customs Clearance, Freight Forwarding, SAP TM, Arabic, Incoterms",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(20),
      createdBy: admin.id,
    },
    {
      title: "Warehouse Supervisor",
      companyName: "Bindawood Holding",
      location: "Jeddah",
      industry: "Retail",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 7,000 – 10,000 / month",
      description: "Manage receiving, storage and dispatch operations for a large FMCG distribution centre.",
      requiredSkills: "WMS, Inventory Control, Team Leadership, Forklift, Safety",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(40),
      createdBy: admin.id,
    },
    {
      title: "Customer Service Representative",
      companyName: "Mobily",
      location: "Riyadh",
      industry: "Telecommunications",
      employmentType: "Full-time",
      experienceRequired: "0-2 years",
      salaryRange: "SAR 4,500 – 6,500 / month",
      description: "Handle inbound calls, resolve billing and technical issues for Mobily subscribers.",
      requiredSkills: "Customer Service, CRM, Arabic, Communication, Problem Solving",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(15),
      createdBy: admin.id,
    },
    {
      title: "Bank Teller",
      companyName: "Al Rajhi Bank",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "0-2 years",
      salaryRange: "SAR 5,000 – 7,000 / month",
      description: "Process transactions, handle cash and provide frontline banking services to customers.",
      requiredSkills: "Cash Handling, Customer Service, Banking Regulations, Attention to Detail",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(20),
      createdBy: admin.id,
    },
    {
      title: "Branch Manager – Banking",
      companyName: "Saudi National Bank",
      location: "Jeddah",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "7-12 years",
      salaryRange: "SAR 22,000 – 30,000 / month",
      description: "Lead a full-service bank branch team to deliver sales targets and excellent customer experience.",
      requiredSkills: "Retail Banking, Team Leadership, Sales, KPIs, Compliance",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(50),
      createdBy: admin.id,
    },
    {
      title: "Real Estate Agent",
      companyName: "JLL Saudi Arabia",
      location: "Riyadh",
      industry: "Real Estate",
      employmentType: "Full-time",
      experienceRequired: "2-5 years",
      salaryRange: "SAR 6,000 + commission",
      description: "Source and negotiate commercial and residential property transactions for high-net-worth clients.",
      requiredSkills: "Real Estate, Negotiation, CRM, Market Analysis, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(35),
      createdBy: admin.id,
    },
    {
      title: "Interior Designer",
      companyName: "Dar Al Handasah",
      location: "Riyadh",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "3-6 years",
      salaryRange: "SAR 10,000 – 15,000 / month",
      description: "Lead interior design concepts for high-end hospitality and commercial fit-out projects.",
      requiredSkills: "AutoCAD, 3ds Max, SketchUp, FF&E, Space Planning",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(45),
      createdBy: admin.id,
    },
    {
      title: "Legal Counsel",
      companyName: "Aramco",
      location: "Dhahran",
      industry: "Oil & Gas",
      employmentType: "Full-time",
      experienceRequired: "5-9 years",
      salaryRange: "SAR 25,000 – 35,000 / month",
      description: "Advise on commercial contracts, regulatory compliance and dispute resolution.",
      requiredSkills: "Corporate Law, Contract Drafting, Saudi Law, Arbitration, English",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(55),
      createdBy: admin.id,
    },
    {
      title: "Administrative Assistant",
      companyName: "Deloitte Saudi Arabia",
      location: "Riyadh",
      industry: "Business Services",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 5,500 – 7,500 / month",
      description: "Provide executive support including scheduling, travel coordination and document management.",
      requiredSkills: "MS Office, Communication, Calendar Management, Arabic, English",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(25),
      createdBy: admin.id,
    },
    {
      title: "Chef – Arabic Cuisine",
      companyName: "Nusret Riyadh",
      location: "Riyadh",
      industry: "Hospitality",
      employmentType: "Full-time",
      experienceRequired: "4-7 years",
      salaryRange: "SAR 9,000 – 13,000 / month",
      description: "Lead the Arabic cold and hot kitchen sections in a premium fine dining restaurant.",
      requiredSkills: "Arabic Cuisine, Kitchen Management, HACCP, Menu Development, Team Leadership",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(30),
      createdBy: admin.id,
    },
    {
      title: "Hotel Front Office Manager",
      companyName: "Marriott Riyadh",
      location: "Riyadh",
      industry: "Hospitality",
      employmentType: "Full-time",
      experienceRequired: "4-6 years",
      salaryRange: "SAR 12,000 – 16,000 / month",
      description: "Oversee guest check-in/out, reservations and front desk team for a 5-star property.",
      requiredSkills: "Opera PMS, Guest Relations, Team Management, Revenue Management, English",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(40),
      createdBy: admin.id,
    },
    {
      title: "Travel Consultant",
      companyName: "Seera Group",
      location: "Jeddah",
      industry: "Tourism",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 6,000 – 9,000 / month",
      description: "Plan and book domestic and international travel packages for individual and corporate clients.",
      requiredSkills: "Amadeus, IATA, Itinerary Planning, Customer Service, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(35),
      createdBy: admin.id,
    },
    {
      title: "Quantity Surveyor",
      companyName: "Red Sea Global",
      location: "Tabuk",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "4-7 years",
      salaryRange: "SAR 14,000 – 20,000 / month",
      description: "Manage cost estimation, procurement and contract administration on Vision 2030 giga-projects.",
      requiredSkills: "Cost Estimation, Primavera, Bills of Quantities, NEC Contracts, RICS",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(60),
      createdBy: admin.id,
    },
    {
      title: "Safety Officer (HSE)",
      companyName: "Saudi Aramco",
      location: "Dammam",
      industry: "Oil & Gas",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 10,000 – 14,000 / month",
      description: "Enforce HSE policies and conduct safety audits and incident investigations on site.",
      requiredSkills: "NEBOSH, Incident Investigation, Risk Assessment, PTW, OSHA",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(45),
      createdBy: admin.id,
    },
    {
      title: "Procurement Specialist",
      companyName: "Maaden",
      location: "Riyadh",
      industry: "Mining",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 11,000 – 16,000 / month",
      description: "Manage vendor selection, RFQ processes and contract negotiations for mining operations.",
      requiredSkills: "SAP MM, Vendor Management, Contract Negotiation, Procurement, Cost Analysis",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(40),
      createdBy: admin.id,
    },
    {
      title: "Business Development Manager",
      companyName: "McKinsey Saudi Arabia",
      location: "Riyadh",
      industry: "Business Services",
      employmentType: "Full-time",
      experienceRequired: "6-10 years",
      salaryRange: "SAR 28,000 – 40,000 / month",
      description: "Lead client relationship development and drive proposal efforts across Vision 2030 sectors.",
      requiredSkills: "Business Development, Consulting, Proposal Writing, Relationship Management, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(50),
      createdBy: admin.id,
    },
    {
      title: "Consultant – Management",
      companyName: "PwC Saudi Arabia",
      location: "Riyadh",
      industry: "Business Services",
      employmentType: "Full-time",
      experienceRequired: "2-5 years",
      salaryRange: "SAR 14,000 – 20,000 / month",
      description: "Deliver strategy and transformation engagements for public sector and energy clients.",
      requiredSkills: "Management Consulting, PowerPoint, Data Analysis, Project Management, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(45),
      createdBy: admin.id,
    },
    {
      title: "Architect",
      companyName: "Neom",
      location: "Tabuk",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 18,000 – 26,000 / month",
      description: "Conceptualize and develop architectural designs for the world's most ambitious urban project.",
      requiredSkills: "Revit, ArchiCAD, Rhino, Parametric Design, Urban Planning",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(60),
      createdBy: admin.id,
    },
    {
      title: "Social Media Manager",
      companyName: "Jarir Bookstore",
      location: "Riyadh",
      industry: "Retail",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 8,000 – 11,000 / month",
      description: "Grow and manage Jarir's social presence across Instagram, Twitter/X, TikTok and Snapchat.",
      requiredSkills: "Social Media, Content Creation, Analytics, Arabic, Campaign Management",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(30),
      createdBy: admin.id,
    },
    {
      title: "Android Developer",
      companyName: "Tabby",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 13,000 – 18,000 / month",
      description: "Build and ship features on the Tabby Android app used by 5M+ shoppers.",
      requiredSkills: "Kotlin, Jetpack Compose, Android SDK, REST APIs, Git",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(35),
      createdBy: admin.id,
    },
    {
      title: "Cloud Solutions Architect",
      companyName: "Oracle Saudi Arabia",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "6-10 years",
      salaryRange: "SAR 25,000 – 35,000 / month",
      description: "Design and propose OCI-based cloud architectures for enterprise government clients.",
      requiredSkills: "OCI, AWS, Azure, Cloud Architecture, Pre-sales, Terraform",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(55),
      createdBy: admin.id,
    },
    {
      title: "QA Engineer",
      companyName: "Foodics",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 10,000 – 14,000 / month",
      description: "Design and execute automated and manual test plans for our restaurant management SaaS.",
      requiredSkills: "Selenium, Cypress, JIRA, API Testing, Agile",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(40),
      createdBy: admin.id,
    },
    {
      title: "Network Engineer",
      companyName: "Zain Saudi Arabia",
      location: "Riyadh",
      industry: "Telecommunications",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 12,000 – 16,000 / month",
      description: "Design, implement and troubleshoot enterprise network infrastructure for telecom customers.",
      requiredSkills: "Cisco, CCNP, BGP, MPLS, Network Security, SD-WAN",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(45),
      createdBy: admin.id,
    },
    {
      title: "ERP Consultant (SAP)",
      companyName: "Accenture Saudi Arabia",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "4-7 years",
      salaryRange: "SAR 16,000 – 23,000 / month",
      description: "Implement and configure SAP S/4HANA modules for large-scale enterprise transformation programs.",
      requiredSkills: "SAP S/4HANA, ABAP, Finance Module, FICO, Client Facing",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: deadline(50),
      createdBy: admin.id,
    },
  ];

  const result = await prisma.job.createMany({ data: jobs });
  console.log(`✓ Added ${result.count} jobs to the database.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
