import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const admin = await prisma.user.findUnique({ where: { email: "admin@saudiacareers.com" } });
  if (!admin) throw new Error("Admin user not found. Run the main seed first.");

  const jobs = [
    // --- Technology ---
    {
      title: "iOS Developer",
      companyName: "Careem Networks",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 16,000 – 22,000 / month",
      description: "Build and maintain Careem's iOS super-app used by millions across the MENA region.\n\nResponsibilities:\n- Own features end-to-end from design review to App Store release\n- Write clean, testable Swift code with MVVM architecture\n- Collaborate with backend engineers on API contracts\n- Triage and resolve production crashes via Crashlytics",
      requiredSkills: "Swift, SwiftUI, UIKit, Xcode, REST APIs, MVVM",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-20"),
      createdBy: admin.id,
    },
    {
      title: "Android Developer",
      companyName: "Careem Networks",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 15,000 – 21,000 / month",
      description: "Develop high-quality Android features for Careem's rider and captain apps.\n\nResponsibilities:\n- Build new screens in Kotlin with Jetpack Compose\n- Integrate REST and WebSocket APIs\n- Write unit and UI tests with JUnit and Espresso\n- Work in two-week sprints with a cross-functional team",
      requiredSkills: "Kotlin, Jetpack Compose, Android SDK, Coroutines, Hilt, JUnit",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-20"),
      createdBy: admin.id,
    },
    {
      title: "Cloud Solutions Architect",
      companyName: "STC Cloud",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "7+ years",
      salaryRange: "SAR 28,000 – 38,000 / month",
      description: "Design cloud migration strategies for enterprise clients moving to STC's hybrid cloud platform.\n\nResponsibilities:\n- Assess on-prem workloads and produce cloud-readiness reports\n- Architect multi-tier solutions on AWS, Azure, and STC Cloud\n- Present technical proposals to C-level stakeholders\n- Lead a team of three cloud engineers during delivery",
      requiredSkills: "AWS, Azure, Terraform, Kubernetes, Network Security, Solution Design",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-30"),
      createdBy: admin.id,
    },
    {
      title: "Full Stack Developer",
      companyName: "Lean Technologies",
      location: "Riyadh",
      industry: "Fintech",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 14,000 – 19,000 / month",
      description: "Build the developer-facing dashboard and internal tooling for Lean's Open Banking APIs.\n\nResponsibilities:\n- Develop React frontend and Node.js backend features\n- Write and maintain PostgreSQL migrations via Prisma\n- Integrate third-party bank APIs and handle OAuth flows\n- Participate in code reviews and technical RFCs",
      requiredSkills: "React, Node.js, TypeScript, PostgreSQL, Prisma, REST APIs",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-31"),
      createdBy: admin.id,
    },
    {
      title: "QA Engineer",
      companyName: "Foodics",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      description: "Ensure quality across Foodics' cloud POS and restaurant management platform.\n\nResponsibilities:\n- Write and maintain automated test suites with Playwright and Cypress\n- Perform exploratory testing on new releases\n- Define and track quality metrics per sprint\n- Work closely with product and engineering to catch issues early",
      requiredSkills: "Playwright, Cypress, Manual Testing, API Testing, Postman, JIRA",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-05"),
      createdBy: admin.id,
    },
    {
      title: "Machine Learning Engineer",
      companyName: "Mozn AI",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 18,000 – 25,000 / month",
      description: "Build and productionise ML models for fraud detection and AML compliance.\n\nResponsibilities:\n- Train and evaluate classification and anomaly-detection models\n- Build MLOps pipelines using MLflow and Kubeflow\n- Collaborate with data engineers on feature pipelines\n- Monitor model drift and trigger retraining workflows",
      requiredSkills: "Python, PyTorch, MLflow, Kubeflow, Feature Engineering, SQL",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-15"),
      createdBy: admin.id,
    },
    {
      title: "Cybersecurity Analyst",
      companyName: "Saudi Telecom (STC)",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 16,000 – 22,000 / month",
      description: "Monitor, detect, and respond to security incidents across STC's enterprise network.\n\nResponsibilities:\n- Operate and tune SIEM (Splunk) for threat detection\n- Conduct threat-hunting exercises and vulnerability assessments\n- Write incident-response playbooks and lead tabletop exercises\n- Coordinate with SOC teams during active incidents",
      requiredSkills: "Splunk, SIEM, MITRE ATT&CK, Vulnerability Assessment, Incident Response, CEH",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-31"),
      createdBy: admin.id,
    },
    {
      title: "Technical Support Engineer",
      companyName: "Unifonic",
      location: "Jeddah",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 8,000 – 11,000 / month",
      description: "Provide technical support to enterprise customers integrating Unifonic's SMS, WhatsApp, and voice APIs.\n\nResponsibilities:\n- Troubleshoot API integration issues via tickets, email, and calls\n- Reproduce bugs and escalate confirmed issues to engineering\n- Write technical guides and update the knowledge base\n- Own first-response SLA for assigned accounts",
      requiredSkills: "REST APIs, Postman, JavaScript basics, Zendesk, Technical Writing",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-25"),
      createdBy: admin.id,
    },

    // --- Finance & Banking ---
    {
      title: "Risk Manager",
      companyName: "Saudi National Bank",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 22,000 – 30,000 / month",
      description: "Lead credit and operational risk assessments for SNB's corporate lending portfolio.\n\nResponsibilities:\n- Review and approve credit risk models and rating methodologies\n- Prepare ICAAP and stress-testing reports for SAMA\n- Manage a team of three risk analysts\n- Liaise with audit and compliance on risk committee deliverables",
      requiredSkills: "Credit Risk, Basel III, ICAAP, Stress Testing, Excel, FRM or CFA",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-01"),
      createdBy: admin.id,
    },
    {
      title: "Treasury Analyst",
      companyName: "SABIC",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 12,000 – 16,000 / month",
      description: "Support SABIC's global treasury operations including cash management, FX hedging, and debt financing.\n\nResponsibilities:\n- Monitor daily cash positions across 40+ bank accounts\n- Execute FX spot and forward transactions\n- Prepare weekly liquidity reports for the CFO\n- Support annual debt issuance and covenant compliance",
      requiredSkills: "Cash Management, FX, Treasury Management Systems, SAP, Excel",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-15"),
      createdBy: admin.id,
    },
    {
      title: "Internal Auditor",
      companyName: "Al Rajhi Bank",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      description: "Conduct risk-based internal audits across Al Rajhi's retail and corporate banking divisions.\n\nResponsibilities:\n- Plan and execute audit engagements per the annual audit plan\n- Document findings and prepare audit reports for management\n- Track remediation of audit recommendations\n- Assess SAMA regulatory compliance",
      requiredSkills: "Internal Audit, Risk-Based Auditing, SAMA Regulations, CIA or CISA, Excel",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-20"),
      createdBy: admin.id,
    },
    {
      title: "Investment Associate",
      companyName: "Public Investment Fund (PIF)",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 18,000 – 26,000 / month",
      description: "Support the direct investments team evaluating and executing Vision 2030 mega-projects.\n\nResponsibilities:\n- Build financial models for infrastructure and private equity deals\n- Conduct market research and competitive benchmarking\n- Prepare IC memos and executive presentations\n- Monitor portfolio company performance and board reporting",
      requiredSkills: "Financial Modelling, Valuation, Private Equity, PowerPoint, CFA (progress)",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-10-01"),
      createdBy: admin.id,
    },

    // --- Healthcare ---
    {
      title: "Registered Nurse – ICU",
      companyName: "King Faisal Specialist Hospital",
      location: "Riyadh",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 9,000 – 13,000 / month",
      description: "Provide expert nursing care for critically ill patients in a 40-bed ICU.\n\nResponsibilities:\n- Manage ventilated, haemodynamically unstable, and post-surgical patients\n- Administer medications and monitor vital signs\n- Coordinate with physicians, respiratory therapists, and dietitians\n- Mentor new nursing staff during orientation",
      requiredSkills: "Critical Care Nursing, Ventilator Management, ACLS, BLS, Saudi MOH License",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-01"),
      createdBy: admin.id,
    },
    {
      title: "Pharmacist",
      companyName: "Nahdi Medical Company",
      location: "Jeddah",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 8,000 – 11,000 / month",
      description: "Dispense medications, counsel patients, and support clinical pharmacy services across Nahdi's retail network.\n\nResponsibilities:\n- Verify prescriptions for accuracy and drug interactions\n- Counsel patients on dosage, side effects, and adherence\n- Maintain controlled-substance logs per SFDA regulations\n- Support vaccination and chronic-disease management clinics",
      requiredSkills: "Clinical Pharmacy, SFDA Regulations, Patient Counselling, PharmD, MOH License",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-31"),
      createdBy: admin.id,
    },
    {
      title: "Radiologist – MRI Technician",
      companyName: "Saudi German Hospital",
      location: "Jeddah",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      description: "Operate MRI scanners and produce high-quality diagnostic images for referring physicians.\n\nResponsibilities:\n- Position patients and select scan protocols for various body regions\n- Maintain MRI equipment and report technical faults\n- Follow radiation safety and infection control protocols\n- Prepare images and preliminary notes for radiologist review",
      requiredSkills: "MRI Operation, ARRT or Equivalent, Patient Positioning, Radiation Safety, MOH License",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-10"),
      createdBy: admin.id,
    },
    {
      title: "Healthcare Data Analyst",
      companyName: "Ministry of Health KSA",
      location: "Riyadh",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 10,000 – 14,000 / month",
      description: "Analyse national health data to inform Vision 2030 healthcare transformation initiatives.\n\nResponsibilities:\n- Build dashboards tracking hospital KPIs and patient outcomes\n- Clean and model large administrative health datasets\n- Produce reports for ministry leadership and WHO\n- Maintain data pipelines from 250+ health facilities",
      requiredSkills: "Python, SQL, Power BI, Healthcare Data Standards, Excel",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-20"),
      createdBy: admin.id,
    },

    // --- Education ---
    {
      title: "Curriculum Designer – STEM",
      companyName: "Misk Foundation",
      location: "Riyadh",
      industry: "Education",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 12,000 – 16,000 / month",
      description: "Design and develop STEM learning experiences for Saudi youth aged 14–22.\n\nResponsibilities:\n- Create project-based curricula aligned with Vision 2030 skills goals\n- Develop assessments and learning rubrics\n- Collaborate with instructional technology team on digital delivery\n- Pilot curricula in Misk's flagship youth programs",
      requiredSkills: "Instructional Design, STEM Education, Curriculum Development, LMS, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-15"),
      createdBy: admin.id,
    },
    {
      title: "English Language Instructor",
      companyName: "British Council Saudi Arabia",
      location: "Jeddah",
      industry: "Education",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 7,000 – 10,000 / month",
      description: "Teach general and business English to adult learners at the Jeddah teaching centre.\n\nResponsibilities:\n- Deliver communicative language teaching classes up to C1 level\n- Plan lessons aligned with Cambridge frameworks\n- Assess students and provide written feedback\n- Support examination preparation for IELTS and Cambridge tests",
      requiredSkills: "CELTA or DELTA, English Language Teaching, IELTS Preparation, Lesson Planning",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-01"),
      createdBy: admin.id,
    },
    {
      title: "E-Learning Developer",
      companyName: "Kholoud Learning",
      location: "Riyadh",
      industry: "Education",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      description: "Produce interactive e-learning modules for corporate clients across the GCC.\n\nResponsibilities:\n- Build SCORM-compliant courses in Articulate Storyline 360\n- Record and edit screen-capture and talking-head videos\n- Work with subject-matter experts to translate content into learnable modules\n- Upload, test, and maintain content on Moodle and Canvas LMS",
      requiredSkills: "Articulate Storyline, SCORM, Video Editing, Adobe Premiere, Moodle, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-10"),
      createdBy: admin.id,
    },

    // --- Retail & Hospitality ---
    {
      title: "Store Manager",
      companyName: "Al-Futtaim Retail",
      location: "Riyadh",
      industry: "Retail",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 14,000 – 19,000 / month",
      description: "Lead all operations for an IKEA flagship store in Riyadh Park Mall.\n\nResponsibilities:\n- Drive sales, conversion, and basket-size KPIs\n- Manage a team of 80 co-workers across departments\n- Execute seasonal range changes and visual merchandising standards\n- Control shrinkage, stockroom accuracy, and P&L",
      requiredSkills: "Retail Management, P&L, Team Leadership, Merchandising, SAP Retail",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-01"),
      createdBy: admin.id,
    },
    {
      title: "Hotel Front Office Manager",
      companyName: "Four Seasons Hotel Riyadh",
      location: "Riyadh",
      industry: "Hospitality",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 15,000 – 20,000 / month",
      description: "Oversee all front-of-house operations for a 5-star luxury hotel in Kingdom Tower.\n\nResponsibilities:\n- Lead check-in, concierge, and guest-relations teams\n- Resolve escalated guest complaints promptly and gracefully\n- Manage room inventory and upselling strategies\n- Prepare daily operational reports for the GM",
      requiredSkills: "Opera PMS, Luxury Hospitality, Team Leadership, Guest Relations, Arabic & English",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-15"),
      createdBy: admin.id,
    },
    {
      title: "F&B Supervisor",
      companyName: "Rotana Hotels",
      location: "Dammam",
      industry: "Hospitality",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 7,000 – 9,500 / month",
      description: "Supervise food and beverage operations across the hotel's two restaurants and in-room dining service.\n\nResponsibilities:\n- Brief and brief service staff at the start of each shift\n- Maintain HACCP standards and daily temperature logs\n- Handle guest feedback and resolve complaints on the floor\n- Assist F&B manager with monthly inventory and ordering",
      requiredSkills: "F&B Service, HACCP, Opera, Upselling, Supervisory Skills, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-20"),
      createdBy: admin.id,
    },
    {
      title: "Procurement Specialist – FMCG",
      companyName: "Savola Group",
      location: "Jeddah",
      industry: "Retail",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 10,000 – 14,000 / month",
      description: "Manage sourcing and supplier relationships for Savola's edible-oils and sugar categories.\n\nResponsibilities:\n- Run RFQ and tender processes for raw-material contracts\n- Negotiate pricing, payment terms, and quality standards\n- Track commodity price indices and recommend hedging decisions\n- Maintain approved supplier list and conduct annual audits",
      requiredSkills: "Procurement, Supplier Management, Negotiation, SAP MM, Commodity Markets",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-01"),
      createdBy: admin.id,
    },

    // --- Engineering & Construction ---
    {
      title: "Electrical Engineer",
      companyName: "Saudi Electricity Company",
      location: "Dammam",
      industry: "Energy",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 14,000 – 18,000 / month",
      description: "Design and commission medium-voltage distribution networks for residential and industrial clients.\n\nResponsibilities:\n- Produce single-line diagrams and cable schedules\n- Review contractor submittals and shop drawings\n- Witness FAT and SAT for switchgear and transformers\n- Support SCADA integration for remote monitoring",
      requiredSkills: "AutoCAD Electrical, MV Distribution, ETAP, IEC Standards, Project Management",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-15"),
      createdBy: admin.id,
    },
    {
      title: "Mechanical Engineer – Rotating Equipment",
      companyName: "Saudi Aramco",
      location: "Dammam",
      industry: "Energy",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 20,000 – 28,000 / month",
      description: "Provide mechanical engineering support for gas-turbine, centrifugal-compressor, and pump overhauls at Aramco's Southern Area Gas Plants.\n\nResponsibilities:\n- Review and approve maintenance work packages\n- Troubleshoot vibration and seal failures\n- Manage OEM warranty claims and technical queries\n- Lead RCA for critical equipment failures",
      requiredSkills: "Rotating Equipment, Reliability Engineering, API 670, SAP PM, RCA",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-10-15"),
      createdBy: admin.id,
    },
    {
      title: "Structural Engineer",
      companyName: "Bechtel Corporation KSA",
      location: "Riyadh",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 15,000 – 20,000 / month",
      description: "Design reinforced concrete and steel structures for large-scale infrastructure projects in Vision 2030 giga-projects.\n\nResponsibilities:\n- Produce structural calculations and drawings in ETABS and SAFE\n- Review sub-contractor design submittals\n- Conduct site inspections and issue technical instructions\n- Coordinate with architect and MEP disciplines on clashes",
      requiredSkills: "ETABS, SAFE, Structural Design, AutoCAD, BIM, Saudi Building Code",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-30"),
      createdBy: admin.id,
    },
    {
      title: "MEP Coordinator",
      companyName: "El Seif Engineering Contracting",
      location: "Riyadh",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      description: "Coordinate mechanical, electrical, and plumbing installation across a 55-floor mixed-use tower in Riyadh.\n\nResponsibilities:\n- Run weekly MEP coordination meetings with sub-contractors\n- Manage clash detection using Navisworks\n- Track RFIs, submittals, and shop drawings\n- Ensure on-time delivery of MEP milestones",
      requiredSkills: "Navisworks, Revit MEP, AutoCAD, RFI Management, MS Project",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-20"),
      createdBy: admin.id,
    },
    {
      title: "HSE Officer",
      companyName: "Almabani General Contractors",
      location: "Other",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 9,000 – 12,000 / month",
      description: "Implement and monitor health, safety, and environmental programs on a NEOM infrastructure project.\n\nResponsibilities:\n- Conduct daily site safety walks and toolbox talks\n- Investigate near-misses and accidents and issue corrective actions\n- Maintain HSE statistics and prepare monthly reports for the client\n- Ensure compliance with Saudi Labour Law and project HSE plan",
      requiredSkills: "NEBOSH, Incident Investigation, Risk Assessment, Saudi Labour Law, MS Office",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-31"),
      createdBy: admin.id,
    },

    // --- Human Resources ---
    {
      title: "HR Business Partner",
      companyName: "Almarai",
      location: "Riyadh",
      industry: "Manufacturing",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 16,000 – 22,000 / month",
      description: "Partner with Almarai's supply-chain and manufacturing leadership to deliver people strategies.\n\nResponsibilities:\n- Advise on organisational design, headcount planning, and succession\n- Lead talent-management and performance-calibration cycles\n- Manage employee relations cases and conduct disciplinary hearings\n- Drive Saudisation compliance across assigned business units",
      requiredSkills: "HR Business Partnering, Talent Management, Labour Law, SAP HCM, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-10"),
      createdBy: admin.id,
    },
    {
      title: "Talent Acquisition Specialist",
      companyName: "stc",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 10,000 – 14,000 / month",
      description: "Manage end-to-end recruitment for technology and commercial roles at stc.\n\nResponsibilities:\n- Source candidates via LinkedIn Recruiter, referrals, and job boards\n- Screen CVs and conduct competency-based interviews\n- Manage offer process and pre-boarding experience\n- Track time-to-fill, acceptance rate, and quality-of-hire metrics",
      requiredSkills: "Recruitment, LinkedIn Recruiter, ATS, Competency-Based Interviewing, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-15"),
      createdBy: admin.id,
    },
    {
      title: "Organisational Development Consultant",
      companyName: "McKinsey & Company",
      location: "Riyadh",
      industry: "Business Services",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 22,000 – 32,000 / month",
      description: "Support Vision 2030 government transformation engagements in workforce design and capability building.\n\nResponsibilities:\n- Conduct job analysis and design competency frameworks\n- Facilitate leadership workshops with ministry and agency clients\n- Build capability-building roadmaps and learning academies\n- Manage workstream delivery on large transformation programmes",
      requiredSkills: "Organisational Design, Change Management, Facilitation, PowerPoint, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-30"),
      createdBy: admin.id,
    },

    // --- Legal & Compliance ---
    {
      title: "Legal Counsel – Corporate",
      companyName: "Saudi Aramco",
      location: "Dammam",
      industry: "Energy",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 24,000 – 33,000 / month",
      description: "Provide legal support on M&A, joint ventures, and commercial contracts for Aramco's downstream and chemicals business.\n\nResponsibilities:\n- Draft and negotiate EPC, JV, and offtake agreements\n- Advise on regulatory matters in Saudi Arabia and international jurisdictions\n- Manage external counsel relationships and legal spend\n- Support IPO-related legal workstreams when required",
      requiredSkills: "Corporate Law, M&A, Contract Drafting, English & Arabic Legal Drafting, Admitted to Saudi Bar",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-10-01"),
      createdBy: admin.id,
    },
    {
      title: "Compliance Officer",
      companyName: "Riyad Bank",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      description: "Monitor and enforce compliance with SAMA regulations, AML/CFT requirements, and internal policies.\n\nResponsibilities:\n- Conduct transaction monitoring reviews and investigate alerts\n- Prepare compliance training and awareness materials\n- Liaise with SAMA examiners during regulatory inspections\n- Maintain and update the compliance risk register",
      requiredSkills: "AML/CFT, SAMA Regulations, Regulatory Compliance, CAMS, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-01"),
      createdBy: admin.id,
    },

    // --- Marketing & Communications ---
    {
      title: "Brand Manager",
      companyName: "Almarai",
      location: "Riyadh",
      industry: "Manufacturing",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 14,000 – 20,000 / month",
      description: "Own the brand strategy and integrated marketing calendar for Almarai's fresh juice and dairy portfolio.\n\nResponsibilities:\n- Lead annual brand planning and A&P budget management\n- Brief and manage creative agencies on campaigns\n- Track brand equity metrics via Nielsen and consumer research\n- Coordinate with trade-marketing on in-store execution",
      requiredSkills: "Brand Management, FMCG Marketing, Nielsen, Agency Management, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-20"),
      createdBy: admin.id,
    },
    {
      title: "Content Creator – Arabic",
      companyName: "Salla",
      location: "Jeddah",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 7,000 – 9,500 / month",
      description: "Produce Arabic-language content that educates Saudi entrepreneurs on e-commerce and Salla's platform.\n\nResponsibilities:\n- Write blog posts, product guides, and social media content in Arabic\n- Script and present short video tutorials for YouTube and TikTok\n- Manage the Arabic content calendar in coordination with product marketing\n- Track content performance and iterate based on analytics",
      requiredSkills: "Arabic Copywriting, Content Marketing, Video Scripting, SEO basics, TikTok, YouTube",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-10"),
      createdBy: admin.id,
    },
    {
      title: "SEO Specialist",
      companyName: "Noon Commerce",
      location: "Riyadh",
      industry: "E-commerce",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      description: "Grow organic traffic to Noon.com across Arabic and English through technical and content SEO.\n\nResponsibilities:\n- Perform site audits and implement technical fixes (Core Web Vitals, schema, crawlability)\n- Identify keyword opportunities and brief the content team\n- Build and report on backlink acquisition campaigns\n- Track performance via Google Search Console and Ahrefs",
      requiredSkills: "Technical SEO, Ahrefs, Google Search Console, HTML basics, Arabic & English",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-05"),
      createdBy: admin.id,
    },
    {
      title: "Public Relations Manager",
      companyName: "Saudi Tourism Authority",
      location: "Riyadh",
      industry: "Tourism",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 18,000 – 25,000 / month",
      description: "Lead PR and media relations for Saudi Tourism Authority's international campaign markets.\n\nResponsibilities:\n- Manage relationships with Tier-1 travel and lifestyle media in GCC and Europe\n- Coordinate press trips, media familiarisation tours, and spokesperson briefings\n- Monitor and report on share-of-voice and sentiment\n- Respond to media enquiries and manage crisis communications",
      requiredSkills: "Media Relations, PR Strategy, Crisis Communications, Travel Media, Arabic & English",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-09-01"),
      createdBy: admin.id,
    },

    // --- Logistics & Transportation ---
    {
      title: "Fleet Operations Manager",
      companyName: "SMSA Express",
      location: "Riyadh",
      industry: "Logistics",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 16,000 – 22,000 / month",
      description: "Manage a fleet of 200+ last-mile delivery vehicles across the Central Region.\n\nResponsibilities:\n- Oversee driver scheduling, route optimisation, and vehicle maintenance\n- Track fleet KPIs: on-time delivery rate, cost per delivery, utilisation\n- Manage fuel card programme and telematics system\n- Lead driver coaching and safety initiatives",
      requiredSkills: "Fleet Management, Route Optimisation, Telematics, KPI Reporting, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-10"),
      createdBy: admin.id,
    },
    {
      title: "Customs Clearance Specialist",
      companyName: "Agility Logistics",
      location: "Dammam",
      industry: "Logistics",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 8,500 – 12,000 / month",
      description: "Process import and export declarations through FASAH and manage customs clearance for Agility's clients at King Abdulaziz Port.\n\nResponsibilities:\n- Prepare and submit customs declarations in FASAH\n- Classify goods under the Saudi Harmonised Tariff Schedule\n- Liaise with Zakat, Tax and Customs Authority (ZATCA) on queries\n- Track shipments and update clients on clearance status",
      requiredSkills: "FASAH, HS Classification, ZATCA Regulations, Import/Export, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-31"),
      createdBy: admin.id,
    },
    {
      title: "Warehouse Supervisor",
      companyName: "Amazon KSA",
      location: "Riyadh",
      industry: "Logistics",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 9,000 – 13,000 / month",
      description: "Supervise inbound and outbound operations in Amazon's Riyadh fulfilment centre.\n\nResponsibilities:\n- Lead a team of 30 associates across pick, pack, and ship processes\n- Monitor hourly productivity rates and coach to target\n- Conduct safety audits and near-miss reporting\n- Manage shift handovers and escalate operational blockers",
      requiredSkills: "Warehouse Operations, WMS, Team Leadership, Inventory Management, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-01"),
      createdBy: admin.id,
    },

    // --- Real Estate ---
    {
      title: "Real Estate Development Manager",
      companyName: "Dar Al Arkan",
      location: "Riyadh",
      industry: "Real Estate",
      employmentType: "Full-time",
      experienceRequired: "7+ years",
      salaryRange: "SAR 25,000 – 35,000 / month",
      description: "Lead the development of residential towers and mixed-use communities in Riyadh's Eastern Ring Road corridor.\n\nResponsibilities:\n- Manage project from land acquisition through handover\n- Coordinate with design, commercial, and construction teams\n- Track development budgets and cashflow forecasts\n- Negotiate with municipalities, utilities, and contractors",
      requiredSkills: "Real Estate Development, Project Management, Financial Modelling, AutoCAD, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-10-15"),
      createdBy: admin.id,
    },
    {
      title: "Property Valuation Analyst",
      companyName: "JLL Saudi Arabia",
      location: "Riyadh",
      industry: "Real Estate",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      description: "Produce property valuations and market research reports for JLL's Saudi client base.\n\nResponsibilities:\n- Conduct desk research and site inspections for residential and commercial assets\n- Build DCF and comparable-sales models\n- Prepare RICS-compliant valuation reports\n- Maintain and update the KSA transaction database",
      requiredSkills: "Property Valuation, DCF Modelling, RICS, Real Estate Market Research, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-08-25"),
      createdBy: admin.id,
    },

    // --- Contract / Part-time / Remote ---
    {
      title: "Freelance Graphic Designer",
      companyName: "Webook",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Contract",
      experienceRequired: "2-4 years",
      description: "Create digital and print assets for Webook's event ticketing platform and client campaigns.\n\nScope:\n- Design social media graphics, banners, and email templates\n- Produce event posters and in-venue branding materials\n- Maintain brand consistency across all touchpoints\n- Deliver assets in 48-hour turnaround on ad-hoc briefs",
      requiredSkills: "Adobe Illustrator, Photoshop, Figma, Motion Graphics, Arabic Typography",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-05"),
      createdBy: admin.id,
    },
    {
      title: "Remote Customer Support Agent – Arabic",
      companyName: "Salla",
      location: "Other",
      industry: "Technology",
      employmentType: "Remote",
      experienceRequired: "0-1 years",
      salaryRange: "SAR 5,000 – 7,000 / month",
      description: "Provide Arabic-language support to Salla's merchant base via live chat, email, and phone.\n\nResponsibilities:\n- Resolve merchant queries on store setup, payments, and shipping\n- Escalate bugs and complex issues to the product team\n- Achieve CSAT score of 90%+ and first-response time under 5 minutes\n- Document recurring issues in the internal knowledge base",
      requiredSkills: "Arabic Customer Support, CRM, Live Chat, Problem Solving",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-20"),
      createdBy: admin.id,
    },
    {
      title: "Part-time Translator – English / Arabic",
      companyName: "Global Health Saudi",
      location: "Jeddah",
      industry: "Healthcare",
      employmentType: "Part-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 3,500 – 5,000 / month",
      description: "Translate medical and regulatory documents between English and Arabic on a part-time basis.\n\nResponsibilities:\n- Translate clinical trial protocols, consent forms, and regulatory submissions\n- Proofread translations against source text for accuracy and terminology\n- Maintain glossary of approved medical terms\n- Meet weekly deliverable schedules",
      requiredSkills: "Medical Translation, English & Arabic, CAT Tools, Proofreading",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-07-31"),
      createdBy: admin.id,
    },

    // --- Older deadline jobs (will show as Closed) ---
    {
      title: "Junior Accountant",
      companyName: "BDO Saudi Arabia",
      location: "Jeddah",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "0-1 years",
      salaryRange: "SAR 5,500 – 7,500 / month",
      description: "Support audit and accounting engagements for BDO's SME client base in the Western Region.",
      requiredSkills: "Accounting, Excel, IFRS basics, VAT, Zoho Books",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-05-30"),
      createdBy: admin.id,
    },
    {
      title: "Sales Representative – Medical Devices",
      companyName: "Medtronic Saudi Arabia",
      location: "Riyadh",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "1-3 years",
      salaryRange: "SAR 9,000 – 13,000 / month",
      description: "Promote and sell Medtronic's cardiac rhythm management portfolio to hospitals in Riyadh.",
      requiredSkills: "Medical Sales, Hospital Selling, CRM, Clinical Presentations, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-06-10"),
      createdBy: admin.id,
    },
    {
      title: "Sous Chef – Arabic Cuisine",
      companyName: "Bayt Al Harees Restaurant Group",
      location: "Riyadh",
      industry: "Hospitality",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "SAR 8,000 – 11,000 / month",
      description: "Lead kitchen operations and menu development for an authentic Saudi fine-dining concept.",
      requiredSkills: "Arabic Cuisine, Kitchen Management, HACCP, Menu Development, Food Costing",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: new Date("2026-06-01"),
      createdBy: admin.id,
    },

    // --- No deadline jobs ---
    {
      title: "Administrative Assistant",
      companyName: "Saudi Chambers of Commerce",
      location: "Riyadh",
      industry: "Business Services",
      employmentType: "Full-time",
      experienceRequired: "0-1 years",
      salaryRange: "SAR 5,000 – 7,000 / month",
      description: "Provide administrative support to the executive office and membership services department.\n\nResponsibilities:\n- Manage calendar, travel, and meeting coordination for two directors\n- Draft correspondence in Arabic and English\n- Maintain physical and digital filing systems\n- Receive and route member enquiries",
      requiredSkills: "Microsoft Office, Arabic & English, Calendar Management, Filing",
      hrEmail: "admin@saudiacareers.com",
      createdBy: admin.id,
    },
    {
      title: "Business Development Manager",
      companyName: "Tahakom",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "5-8 years",
      salaryRange: "SAR 20,000 – 28,000 / month",
      description: "Drive revenue growth by identifying and closing enterprise contracts for Tahakom's smart-traffic and surveillance solutions.\n\nResponsibilities:\n- Build and manage a pipeline of government and municipal clients\n- Lead RFP responses and technical presentations\n- Negotiate contract terms and pricing with procurement departments\n- Represent Tahakom at industry events and exhibitions",
      requiredSkills: "B2G Sales, RFP Management, Solution Selling, Government Relations, Arabic",
      hrEmail: "admin@saudiacareers.com",
      createdBy: admin.id,
    },
    {
      title: "Graphic Designer – Motion",
      companyName: "Impact BBDO Riyadh",
      location: "Riyadh",
      industry: "Business Services",
      employmentType: "Full-time",
      experienceRequired: "2-4 years",
      salaryRange: "SAR 9,000 – 13,000 / month",
      description: "Create motion-graphics and animated assets for digital advertising campaigns targeting Saudi and GCC audiences.\n\nResponsibilities:\n- Design and animate 2D explainers, social reels, and TVC end-frames\n- Collaborate with art directors and copywriters on campaign concepts\n- Adapt international brand assets for Arabic and Saudi cultural context\n- Deliver final files in correct specs for broadcast, digital, and OOH",
      requiredSkills: "After Effects, Premiere Pro, Illustrator, Arabic Typography, Motion Design",
      hrEmail: "admin@saudiacareers.com",
      createdBy: admin.id,
    },
    {
      title: "Environmental Consultant",
      companyName: "Parsons Corporation KSA",
      location: "Other",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      description: "Prepare environmental impact assessments and compliance reports for NEOM and Red Sea Project infrastructure works.\n\nResponsibilities:\n- Conduct baseline environmental surveys (flora, fauna, soil, water)\n- Write ESIA reports to Saudi Environmental Framework standards\n- Liaise with the National Centre for Environmental Compliance\n- Monitor contractor environmental mitigation measures on site",
      requiredSkills: "Environmental Impact Assessment, ESIA, Saudi Environmental Law, GIS, Report Writing",
      hrEmail: "admin@saudiacareers.com",
      createdBy: admin.id,
    },
  ];

  const result = await prisma.job.createMany({ data: jobs });
  console.info(`Inserted ${result.count} sample jobs.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
