import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const now = new Date();
const daysAgo = (d) => new Date(now - d * 86400000);
const future  = (d) => new Date(now.getTime() + d * 86400000);

async function main() {
  const admin = await prisma.user.findUnique({ where: { email: "admin@saudiacareers.com" } });
  if (!admin) throw new Error("Admin user not found. Run the main seed first.");

  const jobs = [
    // ── Salary: Under 5,000 SAR ────────────────────────────────────────────
    {
      title: "Receptionist",
      companyName: "Al Olaya Clinics",
      location: "Riyadh",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "Fresh graduate",
      salaryRange: "Under 5,000 SAR",
      gender: "Female",
      nationality: "Saudi",
      description: "Greet patients, manage appointments, and handle front-desk administration for a busy outpatient clinic.\n\nResponsibilities:\n- Welcome patients and direct them to the correct department\n- Schedule and confirm appointments via phone and online system\n- Maintain confidentiality of patient records",
      requiredSkills: "Communication, MS Office, Customer Service",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(30),
      createdAt: daysAgo(2),
    },
    {
      title: "Warehouse Assistant",
      companyName: "Naqel Express",
      location: "Dammam",
      industry: "Logistics",
      employmentType: "Full-time",
      experienceRequired: "Fresh graduate",
      salaryRange: "Under 5,000 SAR",
      gender: "Male",
      nationality: "Any Nationality",
      description: "Support warehouse operations including receiving, sorting, and dispatching parcels in a fast-paced logistics hub.\n\nResponsibilities:\n- Receive and verify incoming shipments\n- Sort and palletise packages for dispatch\n- Maintain accurate inventory counts",
      requiredSkills: "Physical Fitness, Attention to Detail, Inventory Management",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(45),
      createdAt: daysAgo(1),
    },

    // ── Salary: 5,000 – 10,000 SAR ─────────────────────────────────────────
    {
      title: "Junior Accountant",
      companyName: "Riyad Bank",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "1-2 years",
      salaryRange: "5,000 – 10,000 SAR",
      gender: "Any",
      nationality: "Saudi",
      description: "Assist the finance team with daily bookkeeping, bank reconciliations, and financial reporting.\n\nResponsibilities:\n- Post journal entries and reconcile ledger accounts\n- Prepare monthly expense reports\n- Support external audit preparation",
      requiredSkills: "Accounting, Excel, SAP, IFRS",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(20),
      createdAt: daysAgo(5),
    },
    {
      title: "Graphic Designer",
      companyName: "Jarir Bookstore",
      location: "Jeddah",
      industry: "Retail",
      employmentType: "Full-time",
      experienceRequired: "1-2 years",
      salaryRange: "5,000 – 10,000 SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Create visual content for in-store displays, social media, and digital advertising campaigns.\n\nResponsibilities:\n- Design print and digital marketing materials\n- Collaborate with marketing team on campaign briefs\n- Maintain brand consistency across all touchpoints",
      requiredSkills: "Adobe Illustrator, Photoshop, InDesign, Figma",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(25),
      createdAt: daysAgo(3),
    },
    {
      title: "Customer Support Representative",
      companyName: "stc",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Part-time",
      experienceRequired: "Fresh graduate",
      salaryRange: "5,000 – 10,000 SAR",
      gender: "Any",
      nationality: "Saudi",
      description: "Provide first-line support to stc customers via phone, chat, and email, resolving billing and technical queries.\n\nResponsibilities:\n- Handle inbound customer contacts within SLA targets\n- Escalate complex issues to Tier 2 support\n- Log all interactions in the CRM system",
      requiredSkills: "Customer Service, CRM, Arabic, English",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(60),
      createdAt: daysAgo(0),
    },

    // ── Salary: 10,000 – 15,000 SAR ────────────────────────────────────────
    {
      title: "Marketing Specialist",
      companyName: "Almarai",
      location: "Riyadh",
      industry: "Retail",
      employmentType: "Full-time",
      experienceRequired: "2-3 years",
      salaryRange: "10,000 – 15,000 SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Plan and execute brand campaigns across digital and traditional channels for one of the region's leading FMCG companies.\n\nResponsibilities:\n- Develop monthly content calendars and campaign briefs\n- Manage agency relationships and creative reviews\n- Track and report on campaign KPIs",
      requiredSkills: "Digital Marketing, Google Ads, Meta Ads, Content Strategy",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(30),
      createdAt: daysAgo(7),
    },
    {
      title: "HR Coordinator",
      companyName: "NEOM",
      location: "Other",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "2-3 years",
      salaryRange: "10,000 – 15,000 SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Support HR operations at a giga-project site including recruitment coordination, onboarding, and employee records management.\n\nResponsibilities:\n- Coordinate end-to-end recruitment for site positions\n- Maintain employee files and HRIS data\n- Organise onboarding programmes for new hires",
      requiredSkills: "HRIS, Recruitment, SAP HR, Labour Law",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(45),
      createdAt: daysAgo(10),
    },
    {
      title: "Web Developer",
      companyName: "Foodics",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Contract",
      experienceRequired: "2-3 years",
      salaryRange: "10,000 – 15,000 SAR",
      gender: "Any",
      nationality: "Non-Saudi",
      description: "Build and maintain customer-facing web features for a leading restaurant management SaaS platform.\n\nResponsibilities:\n- Develop React components and REST API integrations\n- Write unit and integration tests\n- Participate in bi-weekly sprint planning and retrospectives",
      requiredSkills: "React, TypeScript, Node.js, REST APIs, Jest",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(15),
      createdAt: daysAgo(4),
    },

    // ── Salary: 15,000 – 20,000 SAR ────────────────────────────────────────
    {
      title: "Civil Engineer",
      companyName: "Saudi Binladin Group",
      location: "Jeddah",
      industry: "Construction",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "15,000 – 20,000 SAR",
      gender: "Male",
      nationality: "Any Nationality",
      description: "Oversee structural and civil works on large-scale commercial and residential construction projects across the Western Region.\n\nResponsibilities:\n- Review and approve technical drawings and shop drawings\n- Coordinate with subcontractors and QA teams\n- Ensure compliance with Saudi Building Code",
      requiredSkills: "AutoCAD, Revit, Project Management, Saudi Building Code",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(30),
      createdAt: daysAgo(6),
    },
    {
      title: "Financial Analyst",
      companyName: "Saudi Tadawul Group",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "15,000 – 20,000 SAR",
      gender: "Any",
      nationality: "Saudi",
      description: "Provide financial modelling and valuation analysis to support investment decisions and market research reports.\n\nResponsibilities:\n- Build and maintain DCF and comparable company models\n- Prepare equity research summaries for institutional clients\n- Monitor sector performance and draft market commentary",
      requiredSkills: "Financial Modelling, Excel, Bloomberg, CFA",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(20),
      createdAt: daysAgo(14),
    },
    {
      title: "Nurse – ICU",
      companyName: "King Faisal Specialist Hospital",
      location: "Riyadh",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "15,000 – 20,000 SAR",
      gender: "Female",
      nationality: "Any Nationality",
      description: "Deliver high-dependency nursing care in the Intensive Care Unit of one of the Kingdom's foremost tertiary hospitals.\n\nResponsibilities:\n- Monitor and manage critically ill patients\n- Administer medications and treatments per physician orders\n- Document patient status and coordinate with multidisciplinary team",
      requiredSkills: "ICU Nursing, BLS, ACLS, Patient Assessment",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(60),
      createdAt: daysAgo(2),
    },
    {
      title: "Software Engineer – Mobile",
      companyName: "Careem",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "3-5 years",
      salaryRange: "15,000 – 20,000 SAR",
      gender: "Any",
      nationality: "Non-Saudi",
      description: "Build new features and maintain the Careem rider and captain apps for millions of users across the MENA region.\n\nResponsibilities:\n- Develop cross-platform features using React Native\n- Collaborate with backend teams on API design\n- Conduct code reviews and improve test coverage",
      requiredSkills: "React Native, iOS, Android, TypeScript, CI/CD",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(40),
      createdAt: daysAgo(1),
    },

    // ── Salary: 20,000 – 30,000 SAR ────────────────────────────────────────
    {
      title: "Senior Data Engineer",
      companyName: "Public Investment Fund",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "5-10 years",
      salaryRange: "20,000 – 30,000 SAR",
      gender: "Any",
      nationality: "Saudi",
      description: "Design and maintain enterprise-scale data pipelines that power PIF's investment analytics platform.\n\nResponsibilities:\n- Architect and build ELT pipelines using Airflow and dbt\n- Optimise query performance on Snowflake data warehouse\n- Establish data quality standards and monitoring",
      requiredSkills: "Python, dbt, Airflow, Snowflake, SQL, AWS",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(30),
      createdAt: daysAgo(20),
    },
    {
      title: "General Practitioner",
      companyName: "Nahdi Medical",
      location: "Jeddah",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "5-10 years",
      salaryRange: "20,000 – 30,000 SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Provide comprehensive primary care to patients across Nahdi's network of community clinics in the Western Region.\n\nResponsibilities:\n- Diagnose and treat acute and chronic conditions\n- Refer patients to specialists when appropriate\n- Maintain accurate electronic medical records",
      requiredSkills: "General Medicine, EMR, Patient Communication, Saudi MOH License",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(90),
      createdAt: daysAgo(3),
    },
    {
      title: "Procurement Manager",
      companyName: "SABIC",
      location: "Dammam",
      industry: "Manufacturing",
      employmentType: "Full-time",
      experienceRequired: "5-10 years",
      salaryRange: "20,000 – 30,000 SAR",
      gender: "Any",
      nationality: "Saudi",
      description: "Lead strategic sourcing and supplier management for raw materials and industrial equipment at SABIC's Eastern Region facilities.\n\nResponsibilities:\n- Develop and execute category strategies for major spend areas\n- Negotiate contracts and SLAs with global suppliers\n- Drive cost reduction and supply chain resilience initiatives",
      requiredSkills: "Strategic Sourcing, SAP MM, Contract Negotiation, CIPS",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(45),
      createdAt: daysAgo(8),
    },
    {
      title: "English Teacher",
      companyName: "International Schools Group",
      location: "Dammam",
      industry: "Education",
      employmentType: "Full-time",
      experienceRequired: "2-3 years",
      salaryRange: "20,000 – 30,000 SAR",
      gender: "Any",
      nationality: "Non-Saudi",
      description: "Teach English Language and Literature to secondary school students following the British National Curriculum.\n\nResponsibilities:\n- Plan and deliver engaging lessons aligned to KS3/KS4 curriculum\n- Assess student progress and provide constructive feedback\n- Communicate regularly with parents about student development",
      requiredSkills: "PGCE, TEFL, British Curriculum, Classroom Management",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(30),
      createdAt: daysAgo(5),
    },

    // ── Salary: 30,000+ SAR ────────────────────────────────────────────────
    {
      title: "Chief Technology Officer",
      companyName: "stc Pay",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "10+ years",
      salaryRange: "30,000+ SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Lead the technology vision and engineering organisation of Saudi Arabia's fastest-growing digital payments platform.\n\nResponsibilities:\n- Define and execute the technology roadmap aligned with business strategy\n- Scale and mentor a 200+ person engineering organisation\n- Own platform reliability, security, and PCI-DSS compliance\n- Represent technology at board level and with regulators",
      requiredSkills: "Engineering Leadership, Cloud Architecture, Payments, PCI-DSS, Fintech",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(60),
      createdAt: daysAgo(0),
    },
    {
      title: "Consultant – Strategy",
      companyName: "McKinsey & Company",
      location: "Riyadh",
      industry: "Finance",
      employmentType: "Full-time",
      experienceRequired: "5-10 years",
      salaryRange: "30,000+ SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Advise Saudi government entities and Vision 2030 programme offices on transformation strategy and execution.\n\nResponsibilities:\n- Lead workstreams on large-scale public sector transformation projects\n- Develop strategic frameworks and implementation roadmaps\n- Build lasting capability within client organisations",
      requiredSkills: "Management Consulting, Strategy, Financial Modelling, Stakeholder Management",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(45),
      createdAt: daysAgo(12),
    },
    {
      title: "Orthopaedic Surgeon",
      companyName: "Saudi German Hospital",
      location: "Jeddah",
      industry: "Healthcare",
      employmentType: "Full-time",
      experienceRequired: "10+ years",
      salaryRange: "30,000+ SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Perform complex orthopaedic procedures and lead a specialist unit at a leading private hospital in Jeddah.\n\nResponsibilities:\n- Perform elective and emergency orthopaedic surgeries\n- Conduct outpatient clinics and follow-up consultations\n- Mentor orthopaedic residents and registrars",
      requiredSkills: "Orthopaedic Surgery, Fellowship, Saudi MOH License, Arabic",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(90),
      createdAt: daysAgo(4),
    },
    {
      title: "VP Engineering",
      companyName: "Salla",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Full-time",
      experienceRequired: "10+ years",
      salaryRange: "30,000+ SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Own the engineering function at Saudi Arabia's leading e-commerce enablement platform as it scales to the next stage of growth.\n\nResponsibilities:\n- Lead 80+ engineers across platform, product, and infrastructure squads\n- Drive technical excellence, hiring, and engineering culture\n- Partner with CPO and CEO on product and technical strategy",
      requiredSkills: "Engineering Management, Distributed Systems, React, Node.js, AWS",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(30),
      createdAt: daysAgo(1),
    },

    // ── Internships ────────────────────────────────────────────────────────
    {
      title: "Marketing Intern",
      companyName: "Tamara Financial",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Internship",
      experienceRequired: "Fresh graduate",
      salaryRange: "Under 5,000 SAR",
      gender: "Any",
      nationality: "Saudi",
      description: "Join Tamara's marketing team for a hands-on internship covering social media, content creation, and campaign support.\n\nResponsibilities:\n- Assist with social media scheduling and community management\n- Support the production of marketing collateral\n- Help analyse campaign performance data",
      requiredSkills: "Social Media, Canva, Content Writing, Analytics",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(20),
      createdAt: daysAgo(0),
    },
    {
      title: "Software Development Intern",
      companyName: "Lean Technologies",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Internship",
      experienceRequired: "Fresh graduate",
      salaryRange: "5,000 – 10,000 SAR",
      gender: "Any",
      nationality: "Any Nationality",
      description: "Work alongside Lean's product engineering team building open-banking infrastructure used by hundreds of fintechs.\n\nResponsibilities:\n- Contribute features and bug fixes across frontend and backend codebases\n- Write automated tests for new functionality\n- Participate in sprint ceremonies and design reviews",
      requiredSkills: "JavaScript, Python, REST APIs, Git",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(25),
      createdAt: daysAgo(2),
    },

    // ── Part-time / Contract variety ───────────────────────────────────────
    {
      title: "Freelance UX Designer",
      companyName: "Geidea",
      location: "Riyadh",
      industry: "Technology",
      employmentType: "Contract",
      experienceRequired: "3-5 years",
      salaryRange: "10,000 – 15,000 SAR",
      gender: "Any",
      nationality: "Non-Saudi",
      description: "Design end-to-end UX flows for Geidea's merchant-facing point-of-sale products on a contract engagement.\n\nResponsibilities:\n- Conduct user research and synthesise insights\n- Create wireframes, prototypes, and high-fidelity designs in Figma\n- Collaborate with product and engineering to ship designs",
      requiredSkills: "Figma, User Research, Prototyping, Design Systems",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(15),
      createdAt: daysAgo(6),
    },
    {
      title: "Part-time Fitness Instructor",
      companyName: "Leejam Sports",
      location: "Jeddah",
      industry: "Retail",
      employmentType: "Part-time",
      experienceRequired: "1-2 years",
      salaryRange: "5,000 – 10,000 SAR",
      gender: "Male",
      nationality: "Any Nationality",
      description: "Lead group fitness classes and provide personalised training at Leejam's flagship Jeddah gym.\n\nResponsibilities:\n- Deliver energetic and safe group exercise sessions\n- Design personalised workout programmes for members\n- Maintain equipment and ensure gym safety standards",
      requiredSkills: "Personal Training, Group Fitness, CPR, Nutrition Basics",
      hrEmail: "admin@saudiacareers.com",
      applicationDeadline: future(30),
      createdAt: daysAgo(9),
    },
  ];

  let created = 0;
  for (const job of jobs) {
    const exists = await prisma.job.findFirst({
      where: { title: job.title, companyName: job.companyName },
    });
    if (!exists) {
      await prisma.job.create({ data: { ...job, createdBy: admin.id } });
      created++;
    }
  }

  console.log(`✓ Seeded ${created} new filter-test jobs (${jobs.length - created} already existed)`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
