// ITU-T E.164 calling codes — priority countries (Gulf + major expat sources) listed first.
// Codes shared by multiple countries (+1, +7) appear once via deduplication in PhoneInput.
export const COUNTRY_CODES = [
  { dialCode: "+966", name: "Saudi Arabia",       priority: true },
  { dialCode: "+971", name: "UAE",                priority: true },
  { dialCode: "+965", name: "Kuwait",             priority: true },
  { dialCode: "+974", name: "Qatar",              priority: true },
  { dialCode: "+973", name: "Bahrain",            priority: true },
  { dialCode: "+968", name: "Oman",               priority: true },
  { dialCode: "+91",  name: "India",              priority: true },
  { dialCode: "+92",  name: "Pakistan",           priority: true },
  { dialCode: "+880", name: "Bangladesh",         priority: true },
  { dialCode: "+63",  name: "Philippines",        priority: true },
  { dialCode: "+20",  name: "Egypt",              priority: true },
  { dialCode: "+962", name: "Jordan",             priority: true },
  { dialCode: "+961", name: "Lebanon",            priority: true },
  { dialCode: "+967", name: "Yemen",              priority: true },
  { dialCode: "+963", name: "Syria",              priority: true },
  { dialCode: "+249", name: "Sudan",              priority: true },
  { dialCode: "+964", name: "Iraq",               priority: true },
  { dialCode: "+212", name: "Morocco",            priority: true },
  { dialCode: "+213", name: "Algeria",            priority: true },
  { dialCode: "+216", name: "Tunisia",            priority: true },

  { dialCode: "+93",  name: "Afghanistan" },
  { dialCode: "+355", name: "Albania" },
  { dialCode: "+244", name: "Angola" },
  { dialCode: "+54",  name: "Argentina" },
  { dialCode: "+374", name: "Armenia" },
  { dialCode: "+61",  name: "Australia" },
  { dialCode: "+43",  name: "Austria" },
  { dialCode: "+994", name: "Azerbaijan" },
  { dialCode: "+375", name: "Belarus" },
  { dialCode: "+32",  name: "Belgium" },
  { dialCode: "+591", name: "Bolivia" },
  { dialCode: "+387", name: "Bosnia" },
  { dialCode: "+55",  name: "Brazil" },
  { dialCode: "+359", name: "Bulgaria" },
  { dialCode: "+855", name: "Cambodia" },
  { dialCode: "+237", name: "Cameroon" },
  { dialCode: "+1",   name: "Canada / USA" },
  { dialCode: "+235", name: "Chad" },
  { dialCode: "+56",  name: "Chile" },
  { dialCode: "+86",  name: "China" },
  { dialCode: "+57",  name: "Colombia" },
  { dialCode: "+506", name: "Costa Rica" },
  { dialCode: "+385", name: "Croatia" },
  { dialCode: "+53",  name: "Cuba" },
  { dialCode: "+357", name: "Cyprus" },
  { dialCode: "+420", name: "Czech Republic" },
  { dialCode: "+45",  name: "Denmark" },
  { dialCode: "+593", name: "Ecuador" },
  { dialCode: "+503", name: "El Salvador" },
  { dialCode: "+372", name: "Estonia" },
  { dialCode: "+251", name: "Ethiopia" },
  { dialCode: "+358", name: "Finland" },
  { dialCode: "+33",  name: "France" },
  { dialCode: "+995", name: "Georgia" },
  { dialCode: "+49",  name: "Germany" },
  { dialCode: "+233", name: "Ghana" },
  { dialCode: "+30",  name: "Greece" },
  { dialCode: "+502", name: "Guatemala" },
  { dialCode: "+509", name: "Haiti" },
  { dialCode: "+504", name: "Honduras" },
  { dialCode: "+36",  name: "Hungary" },
  { dialCode: "+62",  name: "Indonesia" },
  { dialCode: "+98",  name: "Iran" },
  { dialCode: "+353", name: "Ireland" },
  { dialCode: "+972", name: "Israel" },
  { dialCode: "+39",  name: "Italy" },
  { dialCode: "+225", name: "Ivory Coast" },
  { dialCode: "+81",  name: "Japan" },
  { dialCode: "+7",   name: "Kazakhstan / Russia" },
  { dialCode: "+254", name: "Kenya" },
  { dialCode: "+996", name: "Kyrgyzstan" },
  { dialCode: "+371", name: "Latvia" },
  { dialCode: "+218", name: "Libya" },
  { dialCode: "+370", name: "Lithuania" },
  { dialCode: "+352", name: "Luxembourg" },
  { dialCode: "+261", name: "Madagascar" },
  { dialCode: "+60",  name: "Malaysia" },
  { dialCode: "+960", name: "Maldives" },
  { dialCode: "+223", name: "Mali" },
  { dialCode: "+356", name: "Malta" },
  { dialCode: "+52",  name: "Mexico" },
  { dialCode: "+373", name: "Moldova" },
  { dialCode: "+976", name: "Mongolia" },
  { dialCode: "+382", name: "Montenegro" },
  { dialCode: "+258", name: "Mozambique" },
  { dialCode: "+95",  name: "Myanmar" },
  { dialCode: "+977", name: "Nepal" },
  { dialCode: "+31",  name: "Netherlands" },
  { dialCode: "+64",  name: "New Zealand" },
  { dialCode: "+505", name: "Nicaragua" },
  { dialCode: "+234", name: "Nigeria" },
  { dialCode: "+47",  name: "Norway" },
  { dialCode: "+970", name: "Palestine" },
  { dialCode: "+507", name: "Panama" },
  { dialCode: "+675", name: "Papua New Guinea" },
  { dialCode: "+595", name: "Paraguay" },
  { dialCode: "+51",  name: "Peru" },
  { dialCode: "+48",  name: "Poland" },
  { dialCode: "+351", name: "Portugal" },
  { dialCode: "+40",  name: "Romania" },
  { dialCode: "+250", name: "Rwanda" },
  { dialCode: "+221", name: "Senegal" },
  { dialCode: "+381", name: "Serbia" },
  { dialCode: "+65",  name: "Singapore" },
  { dialCode: "+421", name: "Slovakia" },
  { dialCode: "+386", name: "Slovenia" },
  { dialCode: "+252", name: "Somalia" },
  { dialCode: "+27",  name: "South Africa" },
  { dialCode: "+82",  name: "South Korea" },
  { dialCode: "+34",  name: "Spain" },
  { dialCode: "+94",  name: "Sri Lanka" },
  { dialCode: "+46",  name: "Sweden" },
  { dialCode: "+41",  name: "Switzerland" },
  { dialCode: "+886", name: "Taiwan" },
  { dialCode: "+992", name: "Tajikistan" },
  { dialCode: "+255", name: "Tanzania" },
  { dialCode: "+66",  name: "Thailand" },
  { dialCode: "+90",  name: "Turkey" },
  { dialCode: "+993", name: "Turkmenistan" },
  { dialCode: "+256", name: "Uganda" },
  { dialCode: "+380", name: "Ukraine" },
  { dialCode: "+44",  name: "United Kingdom" },
  { dialCode: "+598", name: "Uruguay" },
  { dialCode: "+998", name: "Uzbekistan" },
  { dialCode: "+58",  name: "Venezuela" },
  { dialCode: "+84",  name: "Vietnam" },
  { dialCode: "+260", name: "Zambia" },
  { dialCode: "+263", name: "Zimbabwe" },
];

// Pre-sorted longest-first so +966 is matched before +9 etc. during parsing
const _sorted = [...COUNTRY_CODES].sort((a, b) => b.dialCode.length - a.dialCode.length);

export function parsePhone(value) {
  if (!value) return { code: "+966", digits: "" };
  for (const c of _sorted) {
    if (value.startsWith(c.dialCode)) {
      return { code: c.dialCode, digits: value.slice(c.dialCode.length) };
    }
  }
  return { code: "+966", digits: value.replace(/^\+?/, "") };
}
